// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {PRBMathSD59x18 as P} from "prb-math/PRBMathSD59x18.sol";

/**
 * @notice Library offering the arcsine function. All numbers are fixed-width integer decimals, scaled by 
 * 1e18 to keep convention with ERC20 defaults as well as PRB Math.
 */
library Arcsin {
  using P for int256;

  uint256 constant LOOKUP_TABLE_SIZE = 512;

  /**
   * @notice Checks if a number is within a closed interval, i.e. check $x \in [min, max]$.
   * @param _x The value to check
   * @return Result boolean, true if within the specified [min,max] interval.
  */
  function isWithinBounds(int256 _min, int256 _max, int256 _x) internal pure returns (bool) {
    return _x >= _min || _x <= _max;
  }

  function isWithinBounds(uint256 _min, uint256 _max, uint256 _x) internal pure returns (bool) {
    return _x >= _min || _x <= _max;
  }

/**
  * @notice Gets a value from the arcsine lookup table
  * @dev the table inside of here is generated by the julia script
  * @param _index that is strictly less than the lookup table size
  * @return Result unsigned 32-bits. unsigned since all values on the right side of the arcsine function are nonnegative
 */
  function getFromLookupTable(uint256 _index) internal pure returns (uint64) {
    require(isWithinBounds(0, LOOKUP_TABLE_SIZE-1, _index));

    // 64-bits, since 2^63 allows you to store up to 9.22E18 sizes of decimals, and we use 19 decimal places for the values here
    uint64[LOOKUP_TABLE_SIZE] memory lookup_table;
    lookup_table[0] = 0;
    lookup_table[1] = 1953126241765565;
    lookup_table[2] = 3906259934175676;
    lookup_table[3] = 5859408528130682;
    lookup_table[4] = 7812579475042568;
    lookup_table[5] = 9765780227090818;
    lookup_table[6] = 11719018237478385;
    lookup_table[7] = 13672300960687719;
    lookup_table[8] = 15625635852736949;
    lookup_table[9] = 17579030371436197;
    lookup_table[10] = 19532491976644056;
    lookup_table[11] = 21486028130524290;
    lookup_table[12] = 23439646297802721;
    lookup_table[13] = 25393353946024388;
    lookup_table[14] = 27347158545810948;
    lookup_table[15] = 29301067571118413;
    lookup_table[16] = 31255088499495154;
    lookup_table[17] = 33209228812340286;
    lookup_table[18] = 35163495995162414;
    lookup_table[19] = 37117897537838757;
    lookup_table[20] = 39072440934874712;
    lookup_table[21] = 41027133685663845;
    lookup_table[22] = 42981983294748366;
    lookup_table[23] = 44936997272080080;
    lookup_table[24] = 46892183133281869;
    lookup_table[25] = 48847548399909714;
    lookup_table[26] = 50803100599715309;
    lookup_table[27] = 52758847266909208;
    lookup_table[28] = 54714795942424697;
    lookup_table[29] = 56670954174182206;
    lookup_table[30] = 58627329517354471;
    lookup_table[31] = 60583929534632347;
    lookup_table[32] = 62540761796491387;
    lookup_table[33] = 64497833881459160;
    lookup_table[34] = 66455153376383330;
    lookup_table[35] = 68412727876700538;
    lookup_table[36] = 70370564986706172;
    lookup_table[37] = 72328672319824927;
    lookup_table[38] = 74287057498882328;
    lookup_table[39] = 76245728156377035;
    lookup_table[40] = 78204691934754281;
    lookup_table[41] = 80163956486680121;
    lookup_table[42] = 82123529475316717;
    lookup_table[43] = 84083418574598723;
    lookup_table[44] = 86043631469510620;
    lookup_table[45] = 88004175856365191;
    lookup_table[46] = 89965059443083098;
    lookup_table[47] = 91926289949473605;
    lookup_table[48] = 93887875107516477;
    lookup_table[49] = 95849822661645018;
    lookup_table[50] = 97812140369030409;
    lookup_table[51] = 99774835999867306;
    lookup_table[52] = 101737917337660633;
    lookup_table[53] = 103701392179513838;
    lookup_table[54] = 105665268336418317;
    lookup_table[55] = 107629553633544456;
    lookup_table[56] = 109594255910533803;
    lookup_table[57] = 111559383021792954;
    lookup_table[58] = 113524942836788670;
    lookup_table[59] = 115490943240344729;
    lookup_table[60] = 117457392132940111;
    lookup_table[61] = 119424297431008936;
    lookup_table[62] = 121391667067241832;
    lookup_table[63] = 123359508990889100;
    lookup_table[64] = 125327831168065396;
    lookup_table[65] = 127296641582056308;
    lookup_table[66] = 129265948233626443;
    lookup_table[67] = 131235759141329539;
    lookup_table[68] = 133206082341820076;
    lookup_table[69] = 135176925890167110;
    lookup_table[70] = 137148297860169660;
    lookup_table[71] = 139120206344674174;
    lookup_table[72] = 141092659455893887;
    lookup_table[73] = 143065665325730174;
    lookup_table[74] = 145039232106096094;
    lookup_table[75] = 147013367969241637;
    lookup_table[76] = 148988081108081427;
    lookup_table[77] = 150963379736524378;
    lookup_table[78] = 152939272089805622;
    lookup_table[79] = 154915766424820550;
    lookup_table[80] = 156892871020461205;
    lookup_table[81] = 158870594177954988;
    lookup_table[82] = 160848944221205575;
    lookup_table[83] = 162827929497136398;
    lookup_table[84] = 164807558376036334;
    lookup_table[85] = 166787839251908154;
    lookup_table[86] = 168768780542819130;
    lookup_table[87] = 170750390691254500;
    lookup_table[88] = 172732678164473352;
    lookup_table[89] = 174715651454867171;
    lookup_table[90] = 176699319080321188;
    lookup_table[91] = 178683689584578337;
    lookup_table[92] = 180668771537605966;
    lookup_table[93] = 182654573535965564;
    lookup_table[94] = 184641104203185108;
    lookup_table[95] = 186628372190134534;
    lookup_table[96] = 188616386175404105;
    lookup_table[97] = 190605154865685744;
    lookup_table[98] = 192594686996157560;
    lookup_table[99] = 194584991330871371;
    lookup_table[100] = 196576076663143473;
    lookup_table[101] = 198567951815948579;
    lookup_table[102] = 200560625642317136;
    lookup_table[103] = 202554107025735841;
    lookup_table[104] = 204548404880551649;
    lookup_table[105] = 206543528152379169;
    lookup_table[106] = 208539485818511588;
    lookup_table[107] = 210536286888335061;
    lookup_table[108] = 212533940403746874;
    lookup_table[109] = 214532455439577135;
    lookup_table[110] = 216531841104014217;
    lookup_table[111] = 218532106539034071;
    lookup_table[112] = 220533260920833335;
    lookup_table[113] = 222535313460266254;
    lookup_table[114] = 224538273403285860;
    lookup_table[115] = 226542150031388834;
    lookup_table[116] = 228546952662064706;
    lookup_table[117] = 230552690649249242;
    lookup_table[118] = 232559373383781798;
    lookup_table[119] = 234567010293867451;
    lookup_table[120] = 236575610845542905;
    lookup_table[121] = 238585184543147422;
    lookup_table[122] = 240595740929797852;
    lookup_table[123] = 242607289587868480;
    lookup_table[124] = 244619840139475325;
    lookup_table[125] = 246633402246965477;
    lookup_table[126] = 248647985613410949;
    lookup_table[127] = 250663599983107555;
    lookup_table[128] = 252680255142078647;
    lookup_table[129] = 254697960918584210;
    lookup_table[130] = 256716727183634530;
    lookup_table[131] = 258736563851509671;
    lookup_table[132] = 260757480880283721;
    lookup_table[133] = 262779488272354811;
    lookup_table[134] = 264802596074980301;
    lookup_table[135] = 266826814380817678;
    lookup_table[136] = 268852153328471066;
    lookup_table[137] = 270878623103043337;
    lookup_table[138] = 272906233936694387;
    lookup_table[139] = 274934996109204632;
    lookup_table[140] = 276964919948545440;
    lookup_table[141] = 278996015831454724;
    lookup_table[142] = 281028294184019589;
    lookup_table[143] = 283061765482264416;
    lookup_table[144] = 285096440252746219;
    lookup_table[145] = 287132329073155723;
    lookup_table[146] = 289169442572925650;
    lookup_table[147] = 291207791433845287;
    lookup_table[148] = 293247386390682208;
    lookup_table[149] = 295288238231810551;
    lookup_table[150] = 297330357799846789;
    lookup_table[151] = 299373755992292323;
    lookup_table[152] = 301418443762183463;
    lookup_table[153] = 303464432118748573;
    lookup_table[154] = 305511732128073421;
    lookup_table[155] = 307560354913773148;
    lookup_table[156] = 309610311657672943;
    lookup_table[157] = 311661613600495824;
    lookup_table[158] = 313714272042559084;
    lookup_table[159] = 315768298344478504;
    lookup_table[160] = 317823703927880730;
    lookup_table[161] = 319880500276124635;
    lookup_table[162] = 321938698935030465;
    lookup_table[163] = 323998311513618409;
    lookup_table[164] = 326059349684855337;
    lookup_table[165] = 328121825186411198;
    lookup_table[166] = 330185749821423902;
    lookup_table[167] = 332251135459273983;
    lookup_table[168] = 334317994036368416;
    lookup_table[169] = 336386337556934090;
    lookup_table[170] = 338456178093821169;
    lookup_table[171] = 340527527789316109;
    lookup_table[172] = 342600398855965160;
    lookup_table[173] = 344674803577407429;
    lookup_table[174] = 346750754309219422;
    lookup_table[175] = 348828263479769030;
    lookup_table[176] = 350907343591081111;
    lookup_table[177] = 352988007219713906;
    lookup_table[178] = 355070267017646046;
    lookup_table[179] = 357154135713175780;
    lookup_table[180] = 359239626111830967;
    lookup_table[181] = 361326751097291399;
    lookup_table[182] = 363415523632322435;
    lookup_table[183] = 365505956759721362;
    lookup_table[184] = 367598063603275793;
    lookup_table[185] = 369691857368734556;
    lookup_table[186] = 371787351344791628;
    lookup_table[187] = 373884558904082953;
    lookup_table[188] = 375983493504196187;
    lookup_table[189] = 378084168688694544;
    lookup_table[190] = 380186598088153527;
    lookup_table[191] = 382290795421212359;
    lookup_table[192] = 384396774495639082;
    lookup_table[193] = 386504549209410186;
    lookup_table[194] = 388614133551804963;
    lookup_table[195] = 390725541604515003;
    lookup_table[196] = 392838787542768353;
    lookup_table[197] = 394953885636469826;
    lookup_table[198] = 397070850251356300;
    lookup_table[199] = 399189695850168835;
    lookup_table[200] = 401310436993840502;
    lookup_table[201] = 403433088342701252;
    lookup_table[202] = 405557664657699213;
    lookup_table[203] = 407684180801639595;
    lookup_table[204] = 409812651740441181;
    lookup_table[205] = 411943092544410250;
    lookup_table[206] = 414075518389533048;
    lookup_table[207] = 416209944558786515;
    lookup_table[208] = 418346386443468110;
    lookup_table[209] = 420484859544544676;
    lookup_table[210] = 422625379474020568;
    lookup_table[211] = 424767961956326545;
    lookup_table[212] = 426912622829727695;
    lookup_table[213] = 429059378047753293;
    lookup_table[214] = 431208243680646697;
    lookup_table[215] = 433359235916837282;
    lookup_table[216] = 435512371064433745;
    lookup_table[217] = 437667665552740393;
    lookup_table[218] = 439825135933795075;
    lookup_table[219] = 441984798883931052;
    lookup_table[220] = 444146671205362109;
    lookup_table[221] = 446310769827791498;
    lookup_table[222] = 448477111810045681;
    lookup_table[223] = 450645714341732617;
    lookup_table[224] = 452816594744925582;
    lookup_table[225] = 454989770475873079;
    lookup_table[226] = 457165259126734835;
    lookup_table[227] = 459343078427344786;
    lookup_table[228] = 461523246247001639;
    lookup_table[229] = 463705780596287254;
    lookup_table[230] = 465890699628913330;
    lookup_table[231] = 468078021643597797;
    lookup_table[232] = 470267765085970069;
    lookup_table[233] = 472459948550507158;
    lookup_table[234] = 474654590782500330;
    lookup_table[235] = 476851710680053165;
    lookup_table[236] = 479051327296112051;
    lookup_table[237] = 481253459840528752;
    lookup_table[238] = 483458127682157290;
    lookup_table[239] = 485665350350984015;
    lookup_table[240] = 487875147540292931;
    lookup_table[241] = 490087539108866321;
    lookup_table[242] = 492302545083221688;
    lookup_table[243] = 494520185659885481;
    lookup_table[244] = 496740481207704698;
    lookup_table[245] = 498963452270196672;
    lookup_table[246] = 501189119567938657;
    lookup_table[247] = 503417504000996718;
    lookup_table[248] = 505648626651396538;
    lookup_table[249] = 507882508785635234;
    lookup_table[250] = 510119171857235987;
    lookup_table[251] = 512358637509346626;
    lookup_table[252] = 514600927577382627;
    lookup_table[253] = 516846064091715074;
    lookup_table[254] = 519094069280405246;
    lookup_table[255] = 521344965571987395;
    lookup_table[256] = 523598775598298927;
    lookup_table[257] = 525855522197360203;
    lookup_table[258] = 528115228416305760;
    lookup_table[259] = 530377917514366359;
    lookup_table[260] = 532643612965903901;
    lookup_table[261] = 534912338463500947;
    lookup_table[262] = 537184117921104320;
    lookup_table[263] = 539458975477226210;
    lookup_table[264] = 541736935498202010;
    lookup_table[265] = 544018022581507665;
    lookup_table[266] = 546302261559136859;
    lookup_table[267] = 548589677501039819;
    lookup_table[268] = 550880295718625290;
    lookup_table[269] = 553174141768326799;
    lookup_table[270] = 555471241455234854;
    lookup_table[271] = 557771620836796100;
    lookup_table[272] = 560075306226581970;
    lookup_table[273] = 562382324198127836;
    lookup_table[274] = 564692701588843105;
    lookup_table[275] = 567006465503997359;
    lookup_table[276] = 569323643320779338;
    lookup_table[277] = 571644262692435845;
    lookup_table[278] = 573968351552487488;
    lookup_table[279] = 576295938119027018;
    lookup_table[280] = 578627050899099604;
    lookup_table[281] = 580961718693168927;
    lookup_table[282] = 583299970599668760;
    lookup_table[283] = 585641836019645146;
    lookup_table[284] = 587987344661488720;
    lookup_table[285] = 590336526545760187;
    lookup_table[286] = 592689412010112715;
    lookup_table[287] = 595046031714310808;
    lookup_table[288] = 597406416645350213;
    lookup_table[289] = 599770598122681076;
    lookup_table[290] = 602138607803535453;
    lookup_table[291] = 604510477688363967;
    lookup_table[292] = 606886240126382259;
    lookup_table[293] = 609265927821231568;
    lookup_table[294] = 611649573836755001;
    lookup_table[295] = 614037211602894262;
    lookup_table[296] = 616428874921707171;
    lookup_table[297] = 618824597973511858;
    lookup_table[298] = 621224415323159085;
    lookup_table[299] = 623628361926436892;
    lookup_table[300] = 626036473136610594;
    lookup_table[301] = 628448784711100994;
    lookup_table[302] = 630865332818306701;
    lookup_table[303] = 633286154044571337;
    lookup_table[304] = 635711285401302173;
    lookup_table[305] = 638140764332241317;
    lookup_table[306] = 640574628720897543;
    lookup_table[307] = 643012916898138109;
    lookup_table[308] = 645455667649949882;
    lookup_table[309] = 647902920225370105;
    lookup_table[310] = 650354714344594020;
    lookup_table[311] = 652811090207263689;
    lookup_table[312] = 655272088500942207;
    lookup_table[313] = 657737750409778887;
    lookup_table[314] = 660208117623371615;
    lookup_table[315] = 662683232345829820;
    lookup_table[316] = 665163137305045504;
    lookup_table[317] = 667647875762177767;
    lookup_table[318] = 670137491521356377;
    lookup_table[319] = 672632028939610827;
    lookup_table[320] = 675131532937031653;
    lookup_table[321] = 677636049007170005;
    lookup_table[322] = 680145623227683571;
    lookup_table[323] = 682660302271234642;
    lookup_table[324] = 685180133416648185;
    lookup_table[325] = 687705164560338034;
    lookup_table[326] = 690235444228008754;
    lookup_table[327] = 692771021586640612;
    lookup_table[328] = 695311946456768082;
    lookup_table[329] = 697858269325058123;
    lookup_table[330] = 700410041357199087;
    lookup_table[331] = 702967314411109712;
    lookup_table[332] = 705530141050476511;
    lookup_table[333] = 708098574558630900;
    lookup_table[334] = 710672668952776254;
    lookup_table[335] = 713252478998575690;
    lookup_table[336] = 715838060225111206;
    lookup_table[337] = 718429468940227522;
    lookup_table[338] = 721026762246270048;
    lookup_table[339] = 723629998056232737;
    lookup_table[340] = 726239235110325954;
    lookup_table[341] = 728854532992979642;
    lookup_table[342] = 731475952150295039;
    lookup_table[343] = 734103553907960338;
    lookup_table[344] = 736737400489643868;
    lookup_table[345] = 739377555035882206;
    lookup_table[346] = 742024081623478882;
    lookup_table[347] = 744677045285429884;
    lookup_table[348] = 747336512031395062;
    lookup_table[349] = 750002548868732855;
    lookup_table[350] = 752675223824116779;
    lookup_table[351] = 755354605965755654;
    lookup_table[352] = 758040765426235996;
    lookup_table[353] = 760733773426008786;
    lookup_table[354] = 763433702297544148;
    lookup_table[355] = 766140625510175033;
    lookup_table[356] = 768854617695656106;
    lookup_table[357] = 771575754674462044;
    lookup_table[358] = 774304113482852108;
    lookup_table[359] = 777039772400727857;
    lookup_table[360] = 779782810980313545;
    lookup_table[361] = 782533310075687716;
    lookup_table[362] = 785291351873198429;
    lookup_table[363] = 788057019922793978;
    lookup_table[364] = 790830399170302956;
    lookup_table[365] = 793611575990699314;
    lookup_table[366] = 796400638222389157;
    lookup_table[367] = 799197675202557800;
    lookup_table[368] = 802002777803618505;
    lookup_table[369] = 804816038470802519;
    lookup_table[370] = 807637551260938502;
    lookup_table[371] = 810467411882462963;
    lookup_table[372] = 813305717736713341;
    lookup_table[373] = 816152567960553244;
    lookup_table[374] = 819008063470381575;
    lookup_table[375] = 821872307007582958;
    lookup_table[376] = 824745403185475734;
    lookup_table[377] = 827627458537818717;
    lookup_table[378] = 830518581568941983;
    lookup_table[379] = 833418882805565531;
    lookup_table[380] = 836328474850378756;
    lookup_table[381] = 839247472437452791;
    lookup_table[382] = 842175992489563319;
    lookup_table[383] = 845114154177504684;
    lookup_table[384] = 848062078981481005;
    lookup_table[385] = 851019890754663333;
    lookup_table[386] = 853987715789007229;
    lookup_table[387] = 856965682883429669;
    lookup_table[388] = 859953923414449650;
    lookup_table[389] = 862952571409401070;
    lookup_table[390] = 865961763622335678;
    lookup_table[391] = 868981639612734336;
    lookup_table[392] = 872012341827158366;
    lookup_table[393] = 875054015683973230;
    lookup_table[394] = 878106809661288068;
    lookup_table[395] = 881170875388262886;
    lookup_table[396] = 884246367739939032;
    lookup_table[397] = 887333444935764160;
    lookup_table[398] = 890432268641986324;
    lookup_table[399] = 893543004078105607;
    lookup_table[400] = 896665820127581448;
    lookup_table[401] = 899800889453005404;
    lookup_table[402] = 902948388615960384;
    lookup_table[403] = 906108498201803503;
    lookup_table[404] = 909281402949619122;
    lookup_table[405] = 912467291887609111;
    lookup_table[406] = 915666358474198971;
    lookup_table[407] = 918878800745157154;
    lookup_table[408] = 922104821467046087;
    lookup_table[409] = 925344628297337213;
    lookup_table[410] = 928598433951550950;
    lookup_table[411] = 931866456377799190;
    lookup_table[412] = 935148918939135099;
    lookup_table[413] = 938446050604142989;
    lookup_table[414] = 941758086146225248;
    lookup_table[415] = 945085266352077680;
    lookup_table[416] = 948427838239875975;
    lookup_table[417] = 951786055287731747;
    lookup_table[418] = 955160177673013866;
    lookup_table[419] = 958550472523174601;
    lookup_table[420] = 961957214178762898;
    lookup_table[421] = 965380684469355543;
    lookup_table[422] = 968821173003190816;
    lookup_table[423] = 972278977471344952;
    lookup_table[424] = 975754403967352690;
    lookup_table[425] = 979247767323242035;
    lookup_table[426] = 982759391463024601;
    lookup_table[427] = 986289609774761211;
    lookup_table[428] = 989838765502411566;
    lookup_table[429] = 993407212158765485;
    lookup_table[430] = 996995313960861496;
    lookup_table[431] = 1000603446289404230;
    lookup_table[432] = 1004231996173818420;
    lookup_table[433] = 1007881362804709857;
    lookup_table[434] = 1011551958075646018;
    lookup_table[435] = 1015244207156335898;
    lookup_table[436] = 1018958549099459931;
    lookup_table[437] = 1022695437483594594;
    lookup_table[438] = 1026455341094890450;
    lookup_table[439] = 1030238744650397109;
    lookup_table[440] = 1034046149566185235;
    lookup_table[441] = 1037878074773703974;
    lookup_table[442] = 1041735057588124347;
    lookup_table[443] = 1045617654632774229;
    lookup_table[444] = 1049526442824156414;
    lookup_table[445] = 1053462020422466949;
    lookup_table[446] = 1057425008153023427;
    lookup_table[447] = 1061416050404533573;
    lookup_table[448] = 1065435816510739375;
    lookup_table[449] = 1069485002122634976;
    lookup_table[450] = 1073564330679206646;
    lookup_table[451] = 1077674554985472710;
    lookup_table[452] = 1081816458907549405;
    lookup_table[453] = 1085990859195524738;
    lookup_table[454] = 1090198607446112300;
    lookup_table[455] = 1094440592218409058;
    lookup_table[456] = 1098717741317611907;
    lookup_table[457] = 1103031024263271265;
    lookup_table[458] = 1107381454960638667;
    lookup_table[459] = 1111770094595905700;
    lookup_table[460] = 1116198054778698268;
    lookup_table[461] = 1120666500958128919;
    lookup_table[462] = 1125176656142073739;
    lookup_table[463] = 1129729804953230055;
    lookup_table[464] = 1134327298059977451;
    lookup_table[465] = 1138970557025255070;
    lookup_table[466] = 1143661079622671384;
    lookup_table[467] = 1148400445676066362;
    lookup_table[468] = 1153190323486917190;
    lookup_table[469] = 1158032476923552823;
    lookup_table[470] = 1162928773257394299;
    lookup_table[471] = 1167881191844724276;
    lookup_table[472] = 1172891833768206160;
    lookup_table[473] = 1177962932571071653;
    lookup_table[474] = 1183096866239209177;
    lookup_table[475] = 1188296170613140079;
    lookup_table[476] = 1193563554444088348;
    lookup_table[477] = 1198901916347328234;
    lookup_table[478] = 1204314363953405964;
    lookup_table[479] = 1209804235615782098;
    lookup_table[480] = 1215375125104673160;
    lookup_table[481] = 1221030909804962317;
    lookup_table[482] = 1226775783045638724;
    lookup_table[483] = 1232614291325484057;
    lookup_table[484] = 1238551377372834272;
    lookup_table[485] = 1244592430197210220;
    lookup_table[486] = 1250743343572335409;
    lookup_table[487] = 1257010584753974314;
    lookup_table[488] = 1263401275710393179;
    lookup_table[489] = 1269923289767699526;
    lookup_table[490] = 1276585367403010540;
    lookup_table[491] = 1283397256036160172;
    lookup_table[492] = 1290369880193318552;
    lookup_table[493] = 1297515550518210770;
    lookup_table[494] = 1304848223052125000;
    lookup_table[495] = 1312383824397649779;
    lookup_table[496] = 1320140664458765878;
    lookup_table[497] = 1328139967432274915;
    lookup_table[498] = 1336406565293874804;
    lookup_table[499] = 1344969819025636948;
    lookup_table[500] = 1353864866255387822;
    lookup_table[501] = 1363134348866810841;
    lookup_table[502] = 1372830867595242754;
    lookup_table[503] = 1383020576579863548;
    lookup_table[504] = 1393788640506865573;
    lookup_table[505] = 1405247890121310128;
    lookup_table[506] = 1417553317298780424;
    lookup_table[507] = 1430928095273688250;
    lookup_table[508] = 1445714803201913812;
    lookup_table[509] = 1462490223518405630;
    lookup_table[510] = 1482379181580447236;
    lookup_table[511] = 1508286149795906361;

    return lookup_table[_index];
  }

  /**
    * @notice gets the index in the lookup table based on the x value
    * @param _x The value on the x-axis
    * 
   */
  function findIndex(int256 _x) internal pure returns (uint256) {
    // 1/LOOKUP_TABLE_SIZE
    int256 x_axis_step = P.fromInt(1).div(P.fromInt(int256(LOOKUP_TABLE_SIZE)));
    // floor(x/x_axis_step)
    int256 indexScaled = _x.div(x_axis_step).floor();
    int256 index = P.toInt(indexScaled);

    return uint256(index);
  }

  /**
   * @notice Returns the arcsine of a value
   * @param _x The value to find the arcsine of. Should be bounded inside of [-1,1] scaled by 1e18
   * @return Result scaled by 1e18
   */
  function arcsin(int256 _x) internal pure returns (int256) {
    // initialize constants here since these use functions from a library and so solc cannot ascertain that 
    // they will be compile-time constants
    int256 DOMAIN_MAX = P.fromInt(1);
    int256 DOMAIN_MIN = -DOMAIN_MAX;
    int256 RANGE_MAX = P.pi().div(P.fromInt(2));
    int256 RANGE_MIN = -RANGE_MAX;
    require(isWithinBounds(DOMAIN_MIN, DOMAIN_MAX, _x));

    // arcsine is symmetric around the y-axis, so compute for the range [0, 1] and then reverse answers
    // when necessary
    bool inputIsNegative = _x < 0;
    int256 x = inputIsNegative ? -_x : _x;

    int256 y;
    if (_x == 0) {
      y = 0;
    }
    else if (_x == DOMAIN_MAX) {
      y = RANGE_MAX;
    }
    else {
      // find which indices we need to get from
      // these indices are NOT SCALED BY 1e18!!
      uint256 left_index = findIndex(x);
      uint256 right_index = left_index + 1;

      int256 left_value = int256(int64(getFromLookupTable(left_index)));
      int256 right_value;
      if (left_index == LOOKUP_TABLE_SIZE - 1) {
        right_value = RANGE_MAX;
      }
      else {
        right_value = int256(int64(getFromLookupTable(right_index)));
      }

      y = P.avg(left_value, right_value);
    }

    int256 result = inputIsNegative ? -y : y;

    require(isWithinBounds(RANGE_MIN, RANGE_MAX, result));
    return result;
  }
}
